---
- hosts: apache
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: copying index.html
      copy: src=/root/Anisble_Test1/index.html dest=/var/www/html/index.html
